In [1]:
import pandas as pd
from sklearn.svm import SVC
from matplotlib import pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix
import pickle
from sklearn.preprocessing import LabelEncoder
np.random.seed(1)

In [2]:
df = pd.read_csv("C:/Users/suman/Downloads/RidingMowers.csv") # let's use the same data as we did in the logistic regression example
df.head(3)

   Income  Lot_Size Ownership
0    60.0      18.4     Owner
1    85.5      16.8     Owner
2    64.8      21.6     Owner

In [3]:
# creating instance of labelencoder
labelencoder = LabelEncoder()
# Assigning numerical values and storing in another column
df['Ownership'] = labelencoder.fit_transform(df['Ownership'])
df

    Income  Lot_Size  Ownership
0     60.0      18.4          1
1     85.5      16.8          1
2     64.8      21.6          1
3     61.5      20.8          1
4     87.0      23.6          1
5    110.1      19.2          1
6    108.0      17.6          1
7     82.8      22.4          1
8     69.0      20.0          1
9     93.0      20.8          1
10    51.0      22.0          1
11    81.0      20.0          1
12    75.0      19.6          0
13    52.8      20.8          0
14    64.8      17.2          0
15    43.2      20.4          0
16    84.0      17.6          0
17    49.2      17.6          0
18    59.4      16.0          0
19    66.0      18.4          0
20    47.4      16.4          0
21    33.0      18.8          0
22    51.0      14.0          0
23    63.0      14.8          0

# split should be done here

In [4]:
import sklearn
new_features=df[['Income','Lot_Size','Ownership']]
x=new_features.iloc[:,:-1]
y=new_features.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=5)

In [5]:
performance = pd.DataFrame({"model": [], "Accuracy": [], "Precision": [], "Recall": [], "F1": []})

# Fit a SVM classification model using linear kernal

In [6]:
X_test

    Income  Lot_Size
20    47.4      16.4
2     64.8      21.6
17    49.2      17.6
18    59.4      16.0
19    66.0      18.4
23    63.0      14.8
13    52.8      20.8
10    51.0      22.0

In [7]:
svm_lin_model = SVC(kernel="linear",probability=True)
_ = svm_lin_model.fit(X_train, np.ravel(y_train))

In [8]:
model_preds = svm_lin_model.predict(X_test)
c_matrix = confusion_matrix(y_test, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"linear svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

# Fit a SVM classification model using rbf kernal

In [9]:
svm_rbf_model = SVC(kernel="rbf", C=10, gamma='scale',probability=True)
_ = svm_rbf_model.fit(X_train, np.ravel(y_train))

In [10]:
model_preds = svm_rbf_model.predict(X_test)
c_matrix = confusion_matrix(y_test, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"rbf svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])


# Fit a SVM classification model using polynomial kernal

In [11]:
svm_poly_model = SVC(kernel="poly", degree=3, coef0=1, C=10,probability=True)
_ = svm_poly_model.fit(X_train, np.ravel(y_train))

In [12]:
model_preds = svm_poly_model.predict(X_test)
c_matrix = confusion_matrix(y_test, model_preds)
TP = c_matrix[1][1]
TN = c_matrix[0][0]
FP = c_matrix[0][1]
FN = c_matrix[1][0]
performance = pd.concat([performance, pd.DataFrame({'model':"poly svm", 
                                                    'Accuracy': [(TP+TN)/(TP+TN+FP+FN)], 
                                                    'Precision': [TP/(TP+FP)], 
                                                    'Recall': [TP/(TP+FN)], 
                                                    'F1': [2*TP/(2*TP+FP+FN)]
                                                     }, index=[0])])

In [13]:
## 4.0 Summary

performance

        model  Accuracy  Precision  Recall   F1
0  linear svm     0.875   0.666667     1.0  0.8
0     rbf svm     0.750   0.500000     0.5  0.5
0    poly svm     0.875   0.666667     1.0  0.8

In [14]:
 pickle.dump(svm_lin_model, open('svm_lin_model.pkl', 'wb'))

Accuracy is good for both linear svm and polynoomial svm. Im converting linear svm to pickle file.

In [15]:
# load_model=pickle.load(open('C:/Users/suman/Documents/svm_lin_model.pkl','rb'))

In [16]:
# pred_resuts=load_model.predict([[60.0,18.4]])